USE [master]
GO
/****** Object:  Database [neo]    Script Date: 03/11/2017 15:03:45 ******/

ALTER DATABASE [DB_A1F758_neo] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_A1F758_neo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DB_A1F758_neo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET ARITHABORT OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DB_A1F758_neo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DB_A1F758_neo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DB_A1F758_neo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DB_A1F758_neo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DB_A1F758_neo] SET  MULTI_USER 
GO
ALTER DATABASE [DB_A1F758_neo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DB_A1F758_neo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DB_A1F758_neo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DB_A1F758_neo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DB_A1F758_neo] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DB_A1F758_neo] SET QUERY_STORE = OFF
GO
USE [DB_A1F758_neo]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [DB_A1F758_neo]
GO
USE [DB_A1F758_neo]
GO

/****** Object:  Table [dbo].[Contato]    Script Date: 03/11/2017 15:03:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contato](
	[IdContato] [int] IDENTITY(1,1) NOT NULL,
	[IdEmpresa] [int] NULL,
	[NomeContato] [varchar](250) NULL,
 CONSTRAINT [PK_Contato] PRIMARY KEY CLUSTERED 
(
	[IdContato] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Doc]    Script Date: 03/11/2017 15:03:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Doc](
	[IdDoc] [int] IDENTITY(1,1) NOT NULL,
	[IdSituacaoDoc] [int] NULL,
	[IdTipoDoc] [int] NULL,
	[IdEmpresa] [int] NULL,
	[IdContato] [int] NULL,
	[IdUsuario] [int] NULL,
	[DataCadastro] [datetime] NULL,
	[DataVencimento] [datetime] NULL,
	[NumeroDoc] [varchar](10) NULL,
	[Remessa] [varchar](50) NULL,
	[Vencimento] [varchar](50) NULL,
	[Observacao] [varchar](5000) NULL,
	[SemVencimento] [bit] NULL,
 CONSTRAINT [PK_Doc] PRIMARY KEY CLUSTERED 
(
	[IdDoc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Empresa]    Script Date: 03/11/2017 15:03:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Empresa](
	[IdEmpresa] [int] IDENTITY(1,1) NOT NULL,
	[NomeEmpresa] [varchar](100) NULL,
 CONSTRAINT [PK_Empresa] PRIMARY KEY CLUSTERED 
(
	[IdEmpresa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Item]    Script Date: 03/11/2017 15:03:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Item](
	[IdItem] [int] IDENTITY(1,1) NOT NULL,
	[NomeItem] [varchar](1000) NULL,
	[Valor] [float] NULL,
 CONSTRAINT [PK_Item] PRIMARY KEY CLUSTERED 
(
	[IdItem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ItemDoc]    Script Date: 03/11/2017 15:03:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ItemDoc](
	[IdItemDoc] [int] IDENTITY(1,1) NOT NULL,
	[IdDoc] [int] NULL,
	[IdItem] [int] NULL,
	[Ordem] [int] NULL,
	[Quantidade] [int] NULL,
	[Valor] [float] NULL,
	[Total] [float] NULL,
 CONSTRAINT [PK_ItemCarta] PRIMARY KEY CLUSTERED 
(
	[IdItemDoc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SituacaoDoc]    Script Date: 03/11/2017 15:03:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SituacaoDoc](
	[IdSituacaoDoc] [int] IDENTITY(1,1) NOT NULL,
	[NomeSituacaoDoc] [varchar](50) NULL,
 CONSTRAINT [PK_SituacaoDoc] PRIMARY KEY CLUSTERED 
(
	[IdSituacaoDoc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TipoDoc]    Script Date: 03/11/2017 15:03:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TipoDoc](
	[IdTipoDoc] [int] IDENTITY(1,1) NOT NULL,
	[NomeTipoDoc] [varchar](50) NULL,
 CONSTRAINT [PK_TipoDoc] PRIMARY KEY CLUSTERED 
(
	[IdTipoDoc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 03/11/2017 15:03:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[IdUsuario] [int] IDENTITY(1,1) NOT NULL,
	[NomeUsuario] [varchar](50) NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[IdUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Contato]  WITH CHECK ADD  CONSTRAINT [FK_Contato_Empresa] FOREIGN KEY([IdEmpresa])
REFERENCES [dbo].[Empresa] ([IdEmpresa])
GO
ALTER TABLE [dbo].[Contato] CHECK CONSTRAINT [FK_Contato_Empresa]
GO
ALTER TABLE [dbo].[Doc]  WITH CHECK ADD  CONSTRAINT [FK_Doc_Contato] FOREIGN KEY([IdContato])
REFERENCES [dbo].[Contato] ([IdContato])
GO
ALTER TABLE [dbo].[Doc] CHECK CONSTRAINT [FK_Doc_Contato]
GO
ALTER TABLE [dbo].[Doc]  WITH CHECK ADD  CONSTRAINT [FK_Doc_Empresa] FOREIGN KEY([IdEmpresa])
REFERENCES [dbo].[Empresa] ([IdEmpresa])
GO
ALTER TABLE [dbo].[Doc] CHECK CONSTRAINT [FK_Doc_Empresa]
GO
ALTER TABLE [dbo].[Doc]  WITH CHECK ADD  CONSTRAINT [FK_Doc_SituacaoDoc] FOREIGN KEY([IdSituacaoDoc])
REFERENCES [dbo].[SituacaoDoc] ([IdSituacaoDoc])
GO
ALTER TABLE [dbo].[Doc] CHECK CONSTRAINT [FK_Doc_SituacaoDoc]
GO
ALTER TABLE [dbo].[Doc]  WITH CHECK ADD  CONSTRAINT [FK_Doc_TipoDoc] FOREIGN KEY([IdTipoDoc])
REFERENCES [dbo].[TipoDoc] ([IdTipoDoc])
GO
ALTER TABLE [dbo].[Doc] CHECK CONSTRAINT [FK_Doc_TipoDoc]
GO
ALTER TABLE [dbo].[Doc]  WITH CHECK ADD  CONSTRAINT [FK_Doc_Usuario] FOREIGN KEY([IdUsuario])
REFERENCES [dbo].[Usuario] ([IdUsuario])
GO
ALTER TABLE [dbo].[Doc] CHECK CONSTRAINT [FK_Doc_Usuario]
GO
ALTER TABLE [dbo].[ItemDoc]  WITH CHECK ADD  CONSTRAINT [FK_ItemDoc_Doc] FOREIGN KEY([IdDoc])
REFERENCES [dbo].[Doc] ([IdDoc])
GO
ALTER TABLE [dbo].[ItemDoc] CHECK CONSTRAINT [FK_ItemDoc_Doc]
GO
ALTER TABLE [dbo].[ItemDoc]  WITH CHECK ADD  CONSTRAINT [FK_ItemDoc_Item] FOREIGN KEY([IdItem])
REFERENCES [dbo].[Item] ([IdItem])
GO
ALTER TABLE [dbo].[ItemDoc] CHECK CONSTRAINT [FK_ItemDoc_Item]
GO
USE [master]
GO
ALTER DATABASE [DB_A1F758_neo] SET  READ_WRITE 
GO
